# Generated by Django 4.2.4 on 2023-08-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamientoEducacion',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('join_count', models.FloatField(blank=True, null=True)),
                ('target_fid', models.FloatField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=254, null=True)),
                ('tipologia', models.CharField(blank=True, max_length=50, null=True)),
                ('consultori', models.CharField(blank=True, max_length=254, null=True)),
                ('poblacion', models.FloatField(blank=True, null=True)),
                ('sum_sup_m2', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('sum_sup_to', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipamiento_educacion',
                'managed': False,
            },
        ),
    ]
